### ISSUE TITLE
Issue using sidekiq delayed extensions

### ISSUE THREAD

**Issue by vysakh0** [renz45/mandrill_mailer#35]
I am able to send mails using mandrill mailer, when I try to use sidekiq with `delayed extensions` it does not work.

(UserMailer is Mandrill template mailer here)
`UserMailer.reset_password_instructions(@user, reset_url).deliver` works!

Then based on the readme I added the `app/config/initializers/mandrill_mailer_sidekiq.rb` with

``` ruby
::MandrillMailer::TemplateMailer.extend(Sidekiq::Extensions::ActionMailer)
```

Then tried to deliver the mail asynchronously using `UserMailer.delay.reset_password_instructions(@user, reset_url)` But this throws an error in the sidekiq like this

``` ruby
2014-03-26T04:59:02Z 3520 TID-4ru7wk Sidekiq::Extensions::DelayedMailer JID-669579e667986028f88ed011 INFO: start
2014-03-26T04:59:02Z 3520 TID-4ru7wk Sidekiq::Extensions::DelayedMailer JID-669579e667986028f88ed011 INFO: fail: 0.003 sec
2014-03-26T04:59:02Z 3520 TID-4ru7wk WARN: {"retry"=>true, "queue"=>"default", "class"=>"Sidekiq::Extensions::DelayedMailer", "args"=>["---\n- !ruby/class 'UserMailer'\
n- :reset_password_instructions\n- - !ruby/object:User\n    attributes:\n      id: 1\n      name: cool\n      admin: true\n      email: admin@example.com\n      encrypted
_password: \"$2a$10$G6bXQiLnFA6E3q41lPqlb.LcZxfn/MREIEdlzWgrbIcLR/ilI.CgS\"\n      reset_password_token: c1c56b1d3ebe4566a3c118b671bf39b6e6bc1e9a8e485c976fb01d267401078
1\n      reset_password_sent_at: 2014-03-25 18:25:17.996987000 Z\n      remember_created_at: \n      sign_in_count: 6\n      current_sign_in_at: 2014-03-25 17:53:33.106
915000 Z\n      last_sign_in_at: 2014-03-24 16:40:18.284724000 Z\n      current_sign_in_ip: 127.0.0.1\n      last_sign_in_ip: 127.0.0.1\n      confirmation_token: \n   
   confirmed_at: 2014-03-22 11:16:08.944241000 Z\n      confirmation_sent_at: 2014-03-22 11:16:08.671900000 Z\n      unconfirmed_email: \n      created_at: 2014-03-22 1
1:16:07.895242000 Z\n      updated_at: 2014-03-25 18:25:17.997698000 Z\n      role: \n      receive_order: true\n      receive_tribute: true\n      uploaded_video: true
\n  - http://www.example.com/users/password/edit?reset_password_token=c1c56b1d3ebe4566a3c118b671bf39b6e6bc1e9a8e485c976fb01d2674010781\n"], "jid"=>"669579e667986028f88e
d011", "enqueued_at"=>1395809942.582676, "error_message"=>"undefined method `to' for #<UserMailer:0x23a3dc98>", "error_class"=>"NoMethodError", "failed_at"=>1395809942.
5866923, "retry_count"=>0}
2014-03-26T04:59:02Z 3520 TID-4ru7wk WARN: undefined method `to' for #<UserMailer:0x23a3dc98>
2014-03-26T04:59:02Z 3520 TID-4ru7wk WARN: /home/vysakh/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/bundler/gems/mandrill_mailer-22d69aa347b9/lib/mandrill_mailer/template
_mailer.rb:323:in `method_missing'
/home/vysakh/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/sidekiq-2.17.7/lib/sidekiq/extensions/action_mailer.rb:20:in `perform'
/home/vysakh/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/sidekiq-2.17.7/lib/sidekiq/processor.rb:49:in `block (3 levels) in process'
/home/vysakh/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/sidekiq-2.17.7/lib/sidekiq/middleware/chain.rb:122:in `call'
```

I checked with action mailer, this delay function of sidekiq works! Did i miss something or is this a bug?

**Comment by brunomperes** [comment]
To anyone interested on this, it worked for me using `Model.delay.send_mail`
